sudo: false

language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION.9
    - vendor/cache
    - $HOME/embedded

matrix:
  fast_finish: true

env:
  global:
    - CONCURRENCY=2
    - NOSE_FILTER="not windows"
    - INTEGRATIONS_DIR=$HOME/embedded
    - CHECKSD_OVERRIDE=$TRAVIS_BUILD_DIR/tests/checks/fixtures/checks
    - PIP_CACHE=$HOME/.cache/pip
    - VOLATILE_DIR=/tmp
    - DD_CASHER_DIR=/tmp/casher
  matrix:
    - TRAVIS_FLAVOR=default

# Override travis defaults with empty jobs
before_install:
- rvm install 2.1.5
# before_install: echo "OVERRIDING TRAVIS STEPS"
install: echo "OVERRIDING TRAVIS STEPS"
before_script: echo "OVERRIDING TRAVIS STEPS"

script:
  - bundle install
  - bundle package
  # Needed if no cache exists
  - mkdir -p $INTEGRATIONS_DIR
  - ls -al $INTEGRATIONS_DIR
  - pip install -r requirements.txt
  - mv datadog.conf.example datadog.conf
  - "echo 'api_key: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' >> datadog.conf"
  - nosetests -v tests/core/test_dogstatsd.py:TestServer.test_connection_v4
  - ls -al $INTEGRATIONS_DIR


after_failure:
  - echo "Logs from installation process come here / DEBUG LOGS"
  - cat /tmp/ci.log
